### ISSUE TITLE
Is this still being worked on?

### ISSUE THREAD

**Issue by eklavya** [PaulBGD/react-libui#16]
Hi,

This project looks awesome and could be the panacea for cross platform GUI apps. Is this still being worked on, it would be great if you can provide an update on this.

Thanks 😃

**Comment by PaulBGD** [comment]
I'm the guy who wrote most of this, the reason I've stopped working on it is that libui development is basically stalled. Until libui gets more features, this library won't receive any work from me (not that there's really much work to be done.)

**Comment by eklavya** [comment]
Hi @PaulBGD, thanks for the info. I hope it's completed and production ready some day. Good luck 👍
